- name: Manage EC2 instances
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize compute_details variable
      set_fact:
        compute_details: []

    - name: Extract compute instance details
      set_fact:
        compute_details: >-
          {{
            compute_details + [{
              'id': item.instance_ids[0],
              'private_ip': item.instances[0].private_ip_address,
              'hostname': 'compute_' + (loop.index0 + 1 | string)
            }]
          }}
      loop: "{{ compute_instances.results }}"
      when: item.instance_ids is defined and item.instances is defined
      loop_control:
        label: "{{ loop.index0 }}"

    - name: Debug compute_details
      debug:
        var: compute_details

    - name: Add instance details to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item.private_ip }} {{ item.hostname }}"
        state: present
      loop: "{{ compute_details }}"
      become: yes