---
- name: Install and Configure Slurm on EC2 Instances
  hosts: localhost
  gather_facts: yes
  vars_files:
    - "../compute_details.json"
  tasks:
    - name: Load compute details
      set_fact:
        compute_details: "{{ lookup('file', '../compute_details.json') | from_json }}"

    - name: Set up dynamic inventory
      set_fact:
        inventory: "{{ compute_details | map(attribute='private_ip') | list }}"


# -------------------------------------------------------------------------------
- name: Install and Configure Slurm
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - build-essential
          - libtool
          - autoconf
          - automake
          - bison
          - flex
          - libmunge-dev
          - libpam0g-dev
          - libssl-dev
          - libmariadb-dev
          - libsqlite3-dev
          - pkg-config
          - slurm-client
        state: present
      vars:
        master_ip: "{{ hostvars['master'].private_ip }}"

    - name: Download Slurm source
      get_url:
        url: "https://download.schedmd.com/slurm/slurm-22.05.5.tar.bz2"
        dest: "/tmp/slurm-22.05.5.tar.bz2"

    - name: Extract Slurm source
      unarchive:
        src: "/tmp/slurm-22.05.5.tar.bz2"
        dest: "/tmp/"
        remote_src: yes

    - name: Build and install Slurm
      shell: |
        cd /tmp/slurm-22.05.5
        ./configure --prefix=/usr/local/slurm
        make
        make install
      args:
        chdir: /tmp/slurm-22.05.5

    - name: Create Slurm configuration directory
      file:
        path: "/etc/slurm-llnl"
        state: directory

    - name: Copy Slurm configuration file
      copy:
        src: "config/slurm/slurm.conf.j2"
        dest: "/etc/slurm-llnl/slurm.conf"
        owner: root
        group: root
        mode: '0644'
      # when: ansible_hostname == 'master'
      vars:
        master_ip: "{{ hostvars['master'].private_ip }}"

    - name: Create Slurm systemd service files
      template:
        src: "config/slurm/slurmctld.service.j2"
        dest: "/etc/systemd/system/slurmctld.service"
      vars:
        master_ip: "{{ hostvars['master'].private_ip }}"
      # when: ansible_hostname == 'master' 

    - name: Create slurmd.service file
      template:
        src: "config/slurm/slurmd.service.j2"
        dest: "/etc/systemd/system/slurmd.service"
      vars:
        compute_ip: "{{ hostvars['compute'].private_ip }}"
      # when: ansible_hostname != 'master'
    


    - name: Enable and start Slurm services on master node
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - slurmctld
      vars:
        master_ip: "{{ hostvars['master'].private_ip }}"
      # when: ansible_hostname == 'master'  # or use another condition to identify the master node

    - name: Enable and start Slurm services on compute nodes
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - slurmd
      vars:
        compute_ip: "{{ hostvars['compute'].private_ip }}"
      # when: ansible_hostname != 'master'  # or use another condition to identify compute nodes

    - name: Debug
      debug:
        msg: "Slurm installation and configuration completed on all nodes."
