---
- name: Install and Configure Slurm on EC2 Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - "../compute_details.json"
  tasks:
    - name: Load compute details
      set_fact:
        compute_details: "{{ lookup('file', '../compute_details.json') | from_json }}"

    - name: Set up dynamic inventory
      set_fact:
        inventory: "{{ compute_details | map(attribute='hostname') | list }}"


    - name: Remove old SSH host keys
      command: ssh-keygen -f '/root/.ssh/known_hosts' -R "{{ item }}"
      loop: "{{ inventory }}"
      ignore_errors: yes
      delegate_to: localhost

    # install 
    - name: Ensure all instances are reachable
      wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        delay: 10
      loop: "{{ inventory }}"
      delegate_to: localhost
    
    - name: Test SSH connectivity
      command: ssh -o StrictHostKeyChecking=no -i /root/.ssh/boot-1.pem ubuntu@{{ item }} echo "Connected"
      register: ssh_test
      ignore_errors: yes
      loop: "{{ inventory }}"
      delegate_to: localhost

    - name: Print SSH connectivity results
      debug:
        msg: "{{ ssh_test.results }}"

    - name: Install Slurm on compute nodes
      ansible.builtin.yum:
        name:
          - slurm
          - slurm-slurmd
          - slurm-slurmctld
        state: present
      become: yes
      delegate_to: "{{ item }}"
      loop: "{{ inventory }}"
      vars:
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: /root/.ssh/boot-1.pem

    - name: Copy Slurm configuration files to compute nodes
      ansible.builtin.copy:
        src: "slurm/slurm.conf.j2"
        dest: "/etc/slurm/slurm.conf"
        owner: root
        group: root
        mode: '0644'
      become: yes
      delegate_to: "{{ item }}"
      loop: "{{ inventory }}"
      vars:
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: /root/.ssh/boot-1.pem


    - name: Start and enable Slurm services on compute nodes
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      become: yes
      delegate_to: "{{ item }}"
      loop:
        - slurmctld
        - slurmd
      when: inventory | length > 0
      vars:
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: /root/.ssh/boot-1.pem


    - name: Debug
      debug:
        msg: "Slurm installation and configuration completed on all nodes."
