---
- name: Install and Configure Slurm on EC2 Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - "../compute_details.json"
  tasks:
    - name: Set up dynamic inventory
      set_fact:
        inventory: "{{ compute_details | map(attribute='hostname') | list }}"

    - name: Install and Configure Slurm on the instances
      ansible.builtin.include_tasks:
        file: playbook/install_slurm_tasks.yml
      vars:
        inventory: "{{ inventory }}"