---
- name: Install and Configure Slurm on EC2 Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - "../compute_details.json"
  tasks:
    - name: Load compute details
      set_fact:
        compute_details: "{{ lookup('file', '../compute_details.json') | from_json }}"

    - name: Set up dynamic inventory
      set_fact:
        inventory: "{{ compute_details | map(attribute='hostname') | list }}"
    # install 
    - name: Ensure all instances are reachable
      wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        delay: 10
      loop: "{{ inventory }}"
      delegate_to: localhost

    - name: Install Slurm on compute nodes
      ansible.builtin.yum:
        name:
          - slurm
          - slurm-slurmd
          - slurm-slurmctld
        state: present
      become: yes
      delegate_to: "{{ item }}"
      loop: "{{ inventory }}"

    - name: Copy Slurm configuration files to compute nodes
      ansible.builtin.copy:
        src: "slurm/slurm.conf.j2"
        dest: "/etc/slurm/slurm.conf"
        owner: root
        group: root
        mode: '0644'
      become: yes
      delegate_to: "{{ item }}"
      loop: "{{ inventory }}"

    - name: Start and enable Slurm services on compute nodes
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      become: yes
      delegate_to: "{{ item }}"
      loop:
        - slurmctld
        - slurmd
      when: inventory | length > 0

    - name: Debug
      debug:
        msg: "Slurm installation and configuration completed on all nodes."
